services:
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      # Use "backend" as variable if needed for inter-service communication
      # For now, it's just the API running inside

      # SMTP Settings (Passed from .env)
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=collabry1@gmail.com
      - SPRING_MAIL_PASSWORD=pvhinjfgpjgjoiae
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=*
      - APP_MAIL_FROM=collabry1@gmail.com

    networks:
      - app-network
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      # The backend URL. Since this is read by the BROWSER (client-side),
      # it needs to be localhost if accessed from the host machine browser.
      # If we were doing server-side rendering or proxying, it would be http://backend:9090
      # But for Vite dev server, the browser is on the host.
      - VITE_API_BASE_URL=http://localhost:9090/api/auth
      # Pass the Google Client ID from the host's .env file
      - VITE_GOOGLE_CLIENT_ID=337303186898-c8jdr70o76m93ask0j4nfip2hmh10m3p.apps.googleusercontent.com
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
